services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      NODE_ENV: production
    ports:
      - '3000:3000'
    networks:
      - app-network

  # Aplicación en modo desarrollo
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      NODE_ENV: development
    ports:
      - '3001:3000'
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - development

networks:
  app-network:
    driver: bridge
